<a href="https://colab.research.google.com/github/bonnandrei24/Statistical-Theory-Buenaventura-Repository/blob/main/SummativeAssessment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# ============================================
# STATISTICAL THEORY - PYTHON SOLUTIONS
# ============================================

import pandas as pd
import numpy as np
from scipy import stats

title = "Statistical Theory Summative Assessment"
name  = "Bonn Andrei M. Buenaventura"

print("\n" + "="*70)
print(f"{title:^70}")
print(f"{name:^70}")
print("="*70)

# ============================================
# DATA PREPARATION
# ============================================

males = [
12, 4, 11, 13, 11,
7, 9, 10, 10, 7,
7, 12, 6, 9, 15,
10, 11, 12, 7, 8,
8, 9, 11, 10, 9,
10, 9, 9, 7, 9,
11, 7, 10, 10, 11,
9, 12, 12, 8, 13,
9, 10, 8, 11, 10,
13, 13, 9, 10, 13
]

females = [
11, 9, 7, 10, 9,
10, 10, 7, 9, 10,
11, 8, 9, 6, 11,
10, 7, 9, 12, 14,
11, 12, 12, 8, 12,
12, 9, 10, 11, 7,
12, 7, 9, 8, 11,
10, 8, 13, 8, 10,
9, 9, 9, 11, 9,
9, 8, 9, 12, 11
]

df = pd.DataFrame({
    'Hours': males + females,
    'Gender': ['Male']*50 + ['Female']*50
})

# ============================================
# FUNCTION: DESCRIPTIVE STATISTICS
# ============================================

def get_stats(data):
    n = len(data)
    mean = np.mean(data)
    std_err = stats.sem(data)
    ci_low, ci_high = stats.t.interval(0.95, df=n-1, loc=mean, scale=std_err)

    results = {
        "Mean": mean,
        "Median": np.median(data),
        "Std Dev": np.std(data, ddof=1),
        "Variance": np.var(data, ddof=1),
        "Min": np.min(data),
        "Max": np.max(data),
        "Sample Size": n,
        "Skewness": stats.skew(data, bias=False),
        "Kurtosis": stats.kurtosis(data, bias=False),
        "Q1 (25%)": np.percentile(data, 25),
        "Q2 (50%)": np.percentile(data, 50),
        "Q3 (75%)": np.percentile(data, 75),
        "Deciles": [np.percentile(data, i) for i in range(10, 100, 10)],
        "95% CI Lower": ci_low,
        "95% CI Upper": ci_high
    }

    return pd.Series(results)

# ============================================
# PROBLEM I — DESCRIPTIVE STATISTICS
# ============================================

def format_stats_table(stats_series):
    """Format statistics for cleaner display"""
    stats_df = stats_series.to_frame(name="Value")
    return stats_df.round(4)

# --------------------------------------------
# PROBLEM I.1 — ENTIRE DATASET
# --------------------------------------------
print("\n" + "="*60)
print("PROBLEM I.1 — DESCRIPTIVE STATISTICS (ENTIRE DATASET)")
print("="*60)

overall_stats = get_stats(df['Hours'])
display(format_stats_table(overall_stats))

# --------------------------------------------
# PROBLEM I.2 — GROUPED BY GENDER
# --------------------------------------------
print("\n" + "="*60)
print("PROBLEM I.2 — DESCRIPTIVE STATISTICS (BY GENDER)")
print("="*60)

grouped_stats = df.groupby('Gender')['Hours'].apply(get_stats).unstack()
display(grouped_stats.round(4))

# ============================================
# PROBLEM II — MOMENTS
# ============================================

print("\n=== PROBLEM II: MOMENTS ===")

data_set = np.array([2, 3, 7, 8, 10, 10, 12, 15, 17, 20])
mean_val = np.mean(data_set)

# II.1 Raw Moments (about zero)
m1p = np.mean(data_set**1)
m2p = np.mean(data_set**2)
m3p = np.mean(data_set**3)
m4p = np.mean(data_set**4)

print(f"\nII.1 Raw Moments")
print(f"m1' = {m1p:.4f}")
print(f"m2' = {m2p:.4f}")
print(f"m3' = {m3p:.4f}")
print(f"m4' = {m4p:.4f}")

# II.2 Central Moments (about the mean)
m1 = np.mean((data_set - mean_val)**1)
m2 = np.mean((data_set - mean_val)**2)
m3 = np.mean((data_set - mean_val)**3)
m4 = np.mean((data_set - mean_val)**4)

print(f"\nII.2 Central Moments")
print(f"m1 = {m1:.4f}")
print(f"m2 = {m2:.4f}")
print(f"m3 = {m3:.4f}")
print(f"m4 = {m4:.4f}")

# II.3 Verification Formula
rhs = m4p - 4*m1p*m3p + 6*(m1p**2)*m2p - 3*(m1p**4)

print(f"\nII.3 Verification")
print(f"Central m4        = {m4:.4f}")
print(f"Formula Result    = {rhs:.4f}")
print(f"Match: {np.isclose(m4, rhs)}")

# ============================================
# PROBLEM III — MOMENT RELATIONSHIP PROOF
# ============================================

print("\n=== PROBLEM III: MOMENT RELATIONSHIP PROOF ===")

h = m1p  # mean = first raw moment

rhs_proof = m4 + 4*h*m3 + 6*(h**2)*m2 + h**4

print(f"Raw m4'           = {m4p:.4f}")
print(f"Equation RHS      = {rhs_proof:.4f}")
print(f"Proof Holds: {np.isclose(m4p, rhs_proof)}")

# ============================================
# PROBLEM IV — STUDENT'S t DISTRIBUTION
# ============================================

print("\n=== PROBLEM IV: T-DISTRIBUTION VALUES ===")

# IV.1 Area between -t and t is 0.90, df=20
t1_1 = stats.t.ppf(0.95, df=20)
print(f"IV.1 t-value = {t1_1:.4f}")

# IV.2 Area left of -t is 0.025, df=20
t1_2 = -stats.t.ppf(0.025, df=20)
print(f"IV.2 t-value = {t1_2:.4f}")

# IV.3 Combined tails area = 0.01, df=5
t1_3 = stats.t.ppf(1 - 0.005, df=5)
print(f"IV.3 t-value = {t1_3:.4f}")

# IV.4 Area right of t is 0.55, df=16
t1_4 = stats.t.ppf(0.45, df=16)
print(f"IV.4 t-value = {t1_4:.4f}")

#print("\n" + "="*50)
#print("ALL PROBLEMS SOLVED SUCCESSFULLY")
#print("="*50)

======================================================================
               Statistical Theory Summative Assessment
                     Bonn Andrei M. Buenaventura
======================================================================

============================================================
PROBLEM I.1 — DESCRIPTIVE STATISTICS (ENTIRE DATASET)
============================================================

                                                          Value
Mean                                                       9.76
Median                                                     10.0
Std Dev                                                1.964945
Variance                                                3.86101
Min                                                           4
Max                                                          15
Sample Size                                                 100
Skewness                                              -0.007343
Kurtosis                                               0.015803
Q1 (25%)                                                    9.0
Q2 (50%)                                                   10.0
Q3 (75%)                                                   11.0
Deciles       [7.0, 8.0, 9.0, 9.0, 10.0, 10.0, 11.0, 11.2000...
95% CI Lower                                           9.370112
95% CI Upper                                          10.149888

============================================================
PROBLEM I.2 — DESCRIPTIVE STATISTICS (BY GENDER)
============================================================

,Mean,Median,Std Dev,Variance,Min,Max,Sample Size,Skewness,Kurtosis,Q1 (25%),Q2 (50%),Q3 (75%),Deciles,95% CI Lower,95% CI Upper
Gender,,,,,,,,,,,,,,,
Female,9.7,9.5,1.775686,3.153061,6,14,50,0.134412,-0.441792,9.0,9.5,11.0,"[7.0, 8.0, 9.0, 9.0, 9.5, 10.0, 11.0, 11.0, 12.0]",9.195356,10.204644
Male,9.82,10.0,2.154161,4.640408,4,15,50,-0.114676,0.177262,9.0,10.0,11.0,"[7.0, 8.0, 9.0, 9.0, 10.0, 10.0, 11.0, 12.0, 1...",9.207794,10.432206

=== PROBLEM II: MOMENTS ===

II.1 Raw Moments
m1' = 10.4000
m2' = 138.4000
m3' = 2090.6000
m4' = 34147.6000

II.2 Central Moments
m1 = -0.0000
m2 = 30.2400
m3 = 22.2480
m4 = 1898.9472

II.3 Verification
Central m4        = 1898.9472
Formula Result    = 1898.9472
Match: True

=== PROBLEM III: MOMENT RELATIONSHIP PROOF ===
Raw m4'           = 34147.6000
Equation RHS      = 34147.6000
Proof Holds: True

=== PROBLEM IV: T-DISTRIBUTION VALUES ===
IV.1 t-value = 1.7247
IV.2 t-value = 2.0860
IV.3 t-value = 4.0321
IV.4 t-value = -0.1277